name: 'dbt_ml_preprocessing'
version: '1.1.0'

require-dbt-version: ">=1.0.0"

config-version: 2

profile: "integration_tests"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]
macro-paths: ["macros"]
log-path: "logs"
